<?php
/**
 * @var \DITFramework\Template $this
 */
?>
<div class="ditDebug">

    <?php if(count(\DITFramework\Storage::$errors)>0):
        ?>
        <div class="ditDebugErrors">
            <?php foreach(\DITFramework\Storage::$errors as $error): ?>
                <p>
                    <span><b>Error:</b> <?=$error['message']?></span><br/>
                    <em>File: <?=$error['file']?> (<?=$error['line']?>)</em>
                </p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

</div>
