<?php
/**
 * @project DiT Framework
 * @link http://www.dit-cms.org
 * @author Юрий Сергеевич Селезнев
 * @author Алексей Рубенович Калантарян
 * @var $error
 */
use Core\Library\i18n;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="generator" content="DiT CMS" />
	<style>body{margin:20px;background:#ccc;}#DiT-Fatal-Error{margin-top:50px;padding:1px 10px;color:#de0b15;font-family:Tahoma,sans-serif;font-size:21px;background: #23282D;box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.75);}#DiT-Fatal-Error .hint{color: #ccc;}</style>
</head>
<body>
<div id="DiT-Fatal-Error">
	<p>
		<span><b><?=i18n::t('Fatal error')?>: </b><?=$error['message']?></span><br/>
		<span class="hint"><?=i18n::t('File')?>: <?=$error['file']?> (<?=$error['line']?>)</span>
	</p>
</div>
</body>
</html>